# UrlPath.properties

# App don't need gateway authentication
exclude.urls[0]=/passport/getSMSCode
exclude.urls[1]=/passport/login
exclude.urls[2]=/passport/logout

# SaaS don't need gateway authentication
exclude.urls[3]=/saas/getQRToken
exclude.urls[4]=/saas/scanCode
exclude.urls[5]=/saas/codeHasBeenRead
exclude.urls[6]=/saas/goQRLogin
exclude.urls[7]=/saas/checkLogin
exclude.urls[8]=/saas/info
exclude.urls[9]=/saas/logout

# Admin don't need gateway authentication
exclude.urls[10]=/admin/login
exclude.urls[11]=/admin/logout

# URLs that require IP limit
include.ipLimitUrls[0]=/saas/getQRToken

# URLs that don't need to be authenticated
exclude.urls[12]=/work/port
exclude.urls[13]=/dataDict/app/getItemsByKeys
exclude.urls[14]=/dataDict/app/getItemsByKeys2
exclude.urls[15]=/company/modify
exclude.urls[16]=/resume/refresh
exclude.urls[17]=/tradeOrder/notifyMerchantOrderPaid





# static resources should not be filtered.
exclude.fileRelease=/static/**




