spring:
  datasource:                                     # 数据源的相关配置
    type: com.zaxxer.hikari.HikariDataSource      # 数据源的类型，可以更改为其他的数据源配置，比如druid
    driver-class-name: com.mysql.cj.jdbc.Driver      # mysql/MariaDB 的数据库驱动类名称
    url: jdbc:mysql://localhost:3306/mybosspin?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 33321480
    hikari:
      connection-timeout: 30000               # 等待连接池分配连接的最大时间（毫秒），超过这个时长还没有可用的连接，则会抛出SQLException
      minimum-idle: 5                         # 最小连接数
      maximum-pool-size: 20                   # 最大连接数
      auto-commit: true                       # 自动提交
      idle-timeout: 600000                    # 连接超时的最大时长（毫秒），超时则会被释放（retired）
      pool-name: DataSourceHikariCP           # 连接池的名字
      max-lifetime: 18000000                  # 连接池的最大生命时长（毫秒），超时则会被释放（retired）
      connection-test-query: SELECT 1
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848 # Nacos注册中心的地址
        namespace: decf67bc-7840-4ed9-a65b-6523ffc0fda1 # Nacos的命名空间，我不使用默认的命名空间，而是使用自定义的命名空间

  redis:
    host: localhost
    port: 6379
    password: 33321480
    database: 0

seata:
  enabled: true
  tx-service-group: mybosspin_tx_group # Seata事务组的名称
  service:
    vgroup-mapping:  # 事务组名称与Seata服务组的映射关系
      mybosspin_tx_group: SEATA_GROUP # 事务组名称与Seata服务组的映射关系
    grouplist:  # Seata服务组的列表
      SEATA_GROUP: localhost:8091 # Seata服务组的地址，通常是Seata TC（事务协调器）的地址

  config:
    nacos:
      server-addr: localhost:8848
      namespace: decf67bc-7840-4ed9-a65b-6523ffc0fda1 # Nacos的命名空间
      username: nacos
      password: nacos
  registry:
    nacos:
      server-addr: localhost:8848 # Nacos注册中心的地址
      namespace: decf67bc-7840-4ed9-a65b-6523ffc0fda1 # Nacos的命名空间
      username: nacos
      password: nacos



zookeeper:
  curator:
    #    host: 192.168.1.121:2181,192.168.1.122:2181,192.168.1.123:2181   集群模式
    host: localhost:2181                     # 单机模式
    connectionTimeoutMs: 30000               # 连接超时时间，单位毫秒
    sessionTimeoutMs: 3000                   # 会话超时时间，单位毫秒
    sleepMsBetweenRetry: 2000                # 重试间隔时间，单位毫秒
    maxRetries: 3                            # 最大重试次数
    namespace: curator-mybosspin             # 命名空间，类似于MQ中的Virtual Host

feign:
  sentinel:
    enabled: true                            # 是否启用Feign的Sentinel支持
