server:
#  servlet:
#    context-path: /mybosspin
  port: 8111
  tomcat:
    uri-encoding: utf-8
    max-swallow-size: -1

spring:
  application:
    name: auth-service
  profiles:
    active: dev

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml # 设置MyBatis-Plus的Mapper XML文件位置
  global-config:
    db-config:
      id-type: assign_id
